//
// Generated file, do not edit! Created by opp_msgtool 6.1 from wlasnyMsg.msg.
//

#ifndef __WLASNYMSG_M_H
#define __WLASNYMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class WlasnyMsg;
/**
 * Class generated from <tt>wlasnyMsg.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet WlasnyMsg
 * {
 *     int srcAddress;
 *     int served_hdd;
 *     int wielkoscZadania;
 * }
 * </pre>
 */
class WlasnyMsg : public ::omnetpp::cPacket
{
  protected:
    int srcAddress = 0;
    int served_hdd = 0;
    int wielkoscZadania = 0;

  private:
    void copy(const WlasnyMsg& other);

  protected:
    bool operator==(const WlasnyMsg&) = delete;

  public:
    WlasnyMsg(const char *name=nullptr, short kind=0);
    WlasnyMsg(const WlasnyMsg& other);
    virtual ~WlasnyMsg();
    WlasnyMsg& operator=(const WlasnyMsg& other);
    virtual WlasnyMsg *dup() const override {return new WlasnyMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress);

    virtual int getServed_hdd() const;
    virtual void setServed_hdd(int served_hdd);

    virtual int getWielkoscZadania() const;
    virtual void setWielkoscZadania(int wielkoscZadania);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WlasnyMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WlasnyMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline WlasnyMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<WlasnyMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __WLASNYMSG_M_H

